# Generated by Django 3.1 on 2020-11-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201113_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='listing_active',
            field=models.BooleanField(default=True),
        ),
    ]
