# Generated by Django 3.1 on 2020-11-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlisting_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='listing_winner',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
