# Generated by Django 3.1 on 2020-11-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_highest_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='highest_bid',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='highest_bid',
            field=models.IntegerField(null=True),
        ),
    ]
