# Generated by Django 3.1 on 2020-11-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201114_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='highest_bid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='listing_winner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
