# Generated by Django 3.1 on 2020-11-15 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201114_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidded_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlisting'),
        ),
    ]
