# Generated by Django 3.1 on 2020-11-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid_bidded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='listing_image',
            field=models.URLField(null=True),
        ),
    ]
