# Generated by Django 3.1 on 2020-11-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201115_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='listing_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
