# Generated by Django 3.1 on 2020-11-20 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201117_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='ownerlist',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='ownerlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlisting'),
        ),
    ]
